version: 0.0
os: Windows

files:
  - source: Kubernetes
    destination: C:\Users\sheer\Documents\Projects\Brain-Tasks-App\Kubernetes
  - source: scripts
    destination: C:\Users\sheer\Documents\Projects\Brain-Tasks-App\scripts

hooks:
  ApplicationStart:
    - location: scripts/deploy_to_eks.sh
      timeout: 300
      runas: root